-- MySQL Script generated by MySQL Workbench
-- Qui 01 Set 2016 21:40:51 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema RestaurantesFamosos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RestaurantesFamosos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RestaurantesFamosos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `RestaurantesFamosos` ;

-- -----------------------------------------------------
-- Table `RestaurantesFamosos`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantesFamosos`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantesFamosos`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantesFamosos`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idEstado`),
  INDEX `fk_Estado_Pais1_idx` (`Pais_idPais` ASC),
  CONSTRAINT `fk_Estado_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `mydb`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantesFamosos`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantesFamosos`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_idEstado` ASC),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantesFamosos`.`CEP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantesFamosos`.`CEP` (
  `idCEP` INT NOT NULL AUTO_INCREMENT,
  `Numero` VARCHAR(45) NULL,
  `Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idCEP`),
  INDEX `fk_CEP_Cidade1_idx` (`Cidade_idCidade` ASC),
  CONSTRAINT `fk_CEP_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `mydb`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantesFamosos`.`Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantesFamosos`.`Restaurante` (
  `idRestaurante` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Telefone` VARCHAR(15) NULL,
  `Tipo_de_estabelicimento` VARCHAR(45) NULL,
  `Rua` VARCHAR(45) NULL,
  `Numero` VARCHAR(5) NULL,
  `CEP_idCEP` INT NOT NULL,
  `Tema` VARCHAR(45) NULL,
  PRIMARY KEY (`idRestaurante`),
  INDEX `fk_Restaurante_CEP1_idx` (`CEP_idCEP` ASC),
  CONSTRAINT `fk_Restaurante_CEP1`
    FOREIGN KEY (`CEP_idCEP`)
    REFERENCES `mydb`.`CEP` (`idCEP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantesFamosos`.`Perguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantesFamosos`.`Perguntas` (
  `idPerguntas` INT NOT NULL AUTO_INCREMENT,
  `tempo_de_entrega` VARCHAR(45) NULL,
  `qualidade_do_atendimento` VARCHAR(45) NULL,
  `houve_espera_por_mesa` VARCHAR(45) NULL,
  `aparencia_externa` VARCHAR(45) NULL,
  `aparencia_interna` VARCHAR(45) NULL,
  `limpeza` VARCHAR(45) NULL,
  `variedade_cardapio` VARCHAR(45) NULL,
  `bebidas_alcoolicas` VARCHAR(45) NULL,
  `bebidas_sem_alcool` VARCHAR(45) NULL,
  `pagamento` VARCHAR(45) NULL,
  `qualidade_pelo_valor_pago` VARCHAR(45) NULL,
  PRIMARY KEY (`idPerguntas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantesFamosos`.`Respostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantesFamosos`.`Respostas` (
  `idRespostas` INT NOT NULL AUTO_INCREMENT,
  `Perguntas_idPerguntas` INT NOT NULL,
  PRIMARY KEY (`idRespostas`),
  INDEX `fk_Respostas_Perguntas1_idx` (`Perguntas_idPerguntas` ASC),
  CONSTRAINT `fk_Respostas_Perguntas1`
    FOREIGN KEY (`Perguntas_idPerguntas`)
    REFERENCES `mydb`.`Perguntas` (`idPerguntas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantesFamosos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantesFamosos`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Respostas_idRespostas` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(8) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Respostas1_idx` (`Respostas_idRespostas` ASC),
  CONSTRAINT `fk_Usuario_Respostas1`
    FOREIGN KEY (`Respostas_idRespostas`)
    REFERENCES `mydb`.`Respostas` (`idRespostas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantesFamosos`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantesFamosos`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `Nota_Atendimento` INT NULL,
  `Nota_Comida` INT NULL,
  `Nota_aspecto` INT NULL,
  `Nota_pagamento` INT NULL,
  `Avaliacao Descritiva` INT NULL,
  `Nota_Geral` INT NULL,
  PRIMARY KEY (`idAvaliacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RestaurantesFamosos`.`Visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RestaurantesFamosos`.`Visita` (
  `idVisita` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NULL,
  `Valor Gasto` DOUBLE NULL,
  `Restaurante_idRestaurante` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Avaliacao_idAvaliacao` INT NOT NULL,
  PRIMARY KEY (`idVisita`),
  INDEX `fk_Visita_Restaurante1_idx` (`Restaurante_idRestaurante` ASC),
  INDEX `fk_Visita_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Visita_Avaliacao1_idx` (`Avaliacao_idAvaliacao` ASC),
  CONSTRAINT `fk_Visita_Restaurante1`
    FOREIGN KEY (`Restaurante_idRestaurante`)
    REFERENCES `mydb`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visita_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visita_Avaliacao1`
    FOREIGN KEY (`Avaliacao_idAvaliacao`)
    REFERENCES `mydb`.`Avaliacao` (`idAvaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

create table UF(
	codUF int primary key auto_increment,
    nome varchar(30)
);

select * from UF;